### ISSUE TITLE
Match early vote and day-of polling locations based solely on address

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#108]
Please see the image below. There is an early vote and polling location at the same address, however, the names are different. Because we can't always control the names submitted, can we merge the icons if they have the same address?

*FYI this is staging data

![image](https://cloud.githubusercontent.com/assets/5825049/6276572/c68727f0-b855-11e4-9d33-52cfbe3aa8a5.png)

**Comment by MariaDemocracyWorks** [comment]
I wanted to follow up on the bug Jen identified here, because I'm noticing another interesting behavior around this:
The City of Cave Creek, Arizona (Sample address: 5936 E Chuckwalla Trail, Cave Creek, AZ 85331) has a polling location and an early vote location at 37622 N. Cave Creek Road.

In the data, the Polling Location is named: CAVE CREEK TOWN HALL - ALL MAIL REPLACEMENT SITE ONLY

The early vote site is named: Cave Creek Town Clerk's Office

When I look up the voter address, the name and hours text for the polling location are shown, but with the red bubble indicating an early vote site.  This is especially problematic, since the hours for early voting are different than the hours displayed, which are for election day only.

![screen shot 2015-02-24 at 12 10 04 pm](https://cloud.githubusercontent.com/assets/7061871/6354637/c2f808ee-bc1e-11e4-848e-07a9690801c5.png)

**Comment by jen-tolentino** [comment]
Another item to be aware of is that when a location is "both," as indicated by the green marker, we'll want to display hours and dates for early voting, as well as day-of hours.

**Comment by alexkonrad** [comment]
This is likely because the tool is having trouble matching the two
locations because of their different titles, etc., and so placing two
markers on the map in the same location--the early voting site marker
hiding the polling location marker. I believe we match based on address and
title but for this we may need to match based only on address.

Alex Konrad

**Comment by jungshadow** [comment]
@alexkonrad @MariaDemocracyWorks @jen-tolentino Is it worth investigating redesigning the layout of the info box for locations that serve as both early vote sites and polling locations, especially considering the title and ancillary information may be different/varied?

**Comment by MariaDemocracyWorks** [comment]
It seems like we'll need to do something like that, since displaying the polling place hours for the early vote site is going to be misleading to voters. (You can early vote in Cave Creek today, but not at 6:00am, as the current display in the tool is suggesting.)

**Comment by MariaDemocracyWorks** [comment]
Another thing I'm noticing is that if I click anywhere on the map (other than the red markers) I get an information box with only the name and address of the polling location (but without the hours or "get directions" link).   Is that the intended behavior of the tool?

![screen shot 2015-02-24 at 2 11 34 pm](https://cloud.githubusercontent.com/assets/7061871/6357013/6275d706-bc2f-11e4-9d6a-89f6dd117c65.png)

**Comment by jen-tolentino** [comment]
@alexkonrad in the interim, I think we should match solely on address, but we probably do need to think through and change how we display dates/times for early voting and day-off when they are the same location. What do you think?

We have election data right now, so it would be great to at least get an intermediate fix done soon.

**Comment by jen-tolentino** [comment]
Bump @alexkonrad 

I would be great to get this address soon since the election is on Tuesday. Thanks!

**Comment by alexkonrad** [comment]
I'll work on getting this fixed for this weekend. Let me know if there are
other addresses with this behavior in this upcoming election. Thanks!

Alex Konrad
