### ISSUE TITLE
Search fuction not working for DC address 

### ISSUE THREAD

**Issue by kthale** [votinginfoproject/vip-embeddable-tool#116]
When I go to type in specific address for upcoming 4/28 DC election on VIP projects page (www.votinginfoproject.org) and hit search, nothing happens. However, the self populating address including US works.

Address that does not work: 1325 Jefferson St NW, Washington, DC 
Address that works:  1325 Jefferson St NW, Washington, DC, DC, United States 

![vipsearch](https://cloud.githubusercontent.com/assets/3733857/7354217/c783b81e-ece7-11e4-9379-3619e68e603e.png)
@jen-tolentino

**Comment by jen-tolentino** [comment]
I just wanted to note that this issue seems to be occurring in other tools as well, not just the one embedded at (https://www.votinginfoproject.org/projects/vip-voting-information-tool/). The search icon is no longer clickable, but if you hit "enter" with a valid address, it will bring up information.

We have live tools right now, so it would be great to get this fixed soon -- thank you!

@alexkonrad

**Comment by alexkonrad** [comment]
I've updated this on staging and live.

Alex Konrad

**Comment by jen-tolentino** [comment]
Perfect! Thanks so much for the quick work.
