### ISSUE TITLE
Remove duplicative geocoding 

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#122]
Google just noticed that before submitting user's entered address to the Civic Information API, the tool is making a request to the Google Maps API's Places service to geocode the submitted address, and then submitting that geocoded result to Civic API. There is actually no need to geocode user input before sending it to the Civic Information API; as it will be geocoded it immediately anyway.

It would be great to get this functionality removed, as we noticed its causing some problems with addresses Maps is not able to geocode well, but could be handled by the Civic API.

Thanks!

**Comment by alexkonrad** [comment]
The tool could ether be geocoding as part of the Place Autocomplete we use
for the input box, or in the special case where the current location
functionality kicks in. Do you know if they're referring to the first
situation? (for example, you start typing in your address and then the
Place Autocomplete will try to guess it for you). If it's the first I'm not
sure how we could stop that without removing Place Autocomplete. For the
second, I believe geocoding is necessary in order to position the map to
the current location (though this is an edge case so shouldn't happen very
often). I'll look to see if there's something I'm missing here.

Alex Konrad

**Comment by jen-tolentino** [comment]
Its the first scenario you mention with autocomplete. To give you a little more background, the following address does not work with the autocomplete option, but does work if you just submit the address without selecting.

49 S Barkvine Way Star, ID
(Available for 5/19 election)

From what your describing, it sounds like there isn't really anything we could do, short of removing the Place Autocomplete functionality completely, which I wouldn't want to do since it usually works fine. Are there any other options?

**Comment by alexkonrad** [comment]
It looks like the autocomplete coerces the address to just "S Barkvine Way
Star," even though it displays correctly when you're selecting the address
from the autocomplete dropdown. That's strange, I haven't seen that before.
I agree that it would be preferable to keep the autocomplete.

One option would be to put in a check that prefers the address that
autocomplete puts in the input field (in this case: "49 S Barkvine Way,
Star, ID, United States") over what the autocomplete returns if the value
of the input field contains the value of what autocomplete returns. Unless
there are other instances of the erroneous autocomplete, we would want to
restrict it to that one case because it would become confusing for the user
in the normal cases (for example: you would type in "abc", then select
"abcdef" from the dropdown, but the tool would only use "abc").

Let me know if you guys have found other instances of this. Otherwise I'll
work on adding that additional check.

Alex Konrad

**Comment by jen-tolentino** [comment]
I believe we have definitely had issues with autocomplete returning something different than the entered address, but unfortunately I can't recall any examples right now.

Is there a check you could implement for the scenario when what is selected in the autocomplete drop-down is transformed into something different?

**Comment by alexkonrad** [comment]
The tool is updated to prefer the user inputted address when it is lengthier than the place autocomplete address. If you try entering "49 S Barkvine Way, Star, ID, United States" on the tool for election 4100 you'll see that it correctly grabs the more accurate address.

**Comment by jen-tolentino** [comment]
Perfect, thanks!
