### ISSUE TITLE
[API modification] Add mail-only funtionality

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#149]
The Google Civic API was recently updated and it now will include a "mailOnly": boolean if the election associated with the address is mail-only.

Desired functionality: if mailOnly is present, rather than displaying a polling location, please surface a message that indicates the election is mail only. Right now, I believe the tool would just indicate that no polling location was found.

**Comment by jen-tolentino** [comment]
Here's a test address for EID 4100: 42039 BEELINE HWY Scottsdale, AZ 85262

**Comment by jen-tolentino** [comment]
I wanted to bump this since we have an upcoming mail-only election. You can view sample data in the staging tool using this adding: 490 Canyon Springs Rd, Prescott, AZ 86303

**Comment by alexkonrad** [comment]
@jen-tolentino the AZ address you supplied has the mailOnly: true option, but it also surfaces two drop-off locations. Is that the correct result? Then, if we display drop-off locations, should we also add a message about the mail-in only functionality?

**Comment by jungshadow** [comment]
@alexkonrad Surfacing the mail-only pop-up is a good idea. In states where drop off locations are not guaranteed to be statewide like OR and WA and we don't know what the administrative process is for a voter dropping off a ballot at a county clerk's office in a different county, the "Use Current Location" and "Enter a Different Address" buttons have to be removed (i.e. leaving only "Continue). In addition, in the initial popup, the content should say (thanks to @jen-tolentino and @greenesd for edits to the content):

> Your upcoming election is mail-only. Please contact your local election official to learn more about how to receive and return your ballot:
> [ALL LEO INFO AVAILABLE IN A DIGESTIBLE FORM, ESPECIALLY FOR SMALL SCREEN]
> This also means you may be able to return your ballot at multiple locations. Please hit continue to see your election information.

The capabilities of the polling location should be in the API response pollingLocations[].voterServices field and should be exposed in the listing (_**NB:** if memory serves, it already is_). If the pollingLocations[].voterServices field is not populated and the flag mailOnly is set (_**NB:** technically this is a fluke, but I want to account for it_), the text "mail ballot drop off" will have to be indicated somewhere in the listing. Does that make sense?

**Comment by alexkonrad** [comment]
@acohen84 I'd like to get some confirmation on this before I move these changes live and close out this issue.

We currently have a "Current Location" selector for WA and OR, which you'll see when you input an address and allows you to choose the option to view polling locations that are closet to your current location instead of your registered address, provided your current location is within the relevant state.

On the staging tool we have the new mail-only functionality, which instead of the current location selector just shows you the message and then allows you to proceed just like before.

You can see this mail-only functionality on the [configurable staging tool](http://s3.amazonaws.com/vip-voter-information-tool-staging/configurable.html) for EID 4100 with this address: 5028 37th Ave NE, Seattle, WA 98105.

Compare with the current location functionality on the [live tool](http://s3.amazonaws.com/vip-voter-information-tool/configurable.html) with same EID and address.

When I merge this into production the mail-only feature will override the current location. We also have the option to remove the current location feature if the mail-only feature is intended to replace this functionality.

**Comment by acohen84** [comment]
Thanks Alex.

- OR and WA need to have the Current Location selector.  It sounds like we might need to hard code this in because they are also using the mail-only flag.
- For other states that are using the mail-only flag, the mail-only text that pops up is okay generally, but can we provide more information - or at least more context - than just the phone number?  It doesn't even say who the phone number belongs to right now.

**Comment by alexkonrad** [comment]
Thanks Amy!

- We'll display the mail-only text unless the state is WA or OR, in which case we'll display the current location selector.
- I've noticed that too (only the phone number). Currently we're looking for the Election Official information in the API path `local_jurisdiction.electionAdministrationBody.electionOfficials` and for a lot addresses (at least in the test data) it only returns a phone number. I set it to look for information in that path because Jared requested "all LEO info" above. I could add the URL for the Election Administration Body too, or even other URLs, but if there's something else that would be more appropriate let me know.

**Comment by acohen84** [comment]
Plus @mariabianchi

Maria, can you assuage my brain and confirm that Colorado will not be negatively impacted by this change?

For the election official information:
- If there's no local election official, it should provide contact info for the state, even though that won't be as helpful as a local.
- Maria is much more familiar with the API, so I'll ask her to weigh in about the right place to look for info.

**Comment by MariaBianchi** [comment]
Currently, I don't believe Colorado uses the mail only flag, so this shouldn't impact them. That said, they definitely should be using that flag since they are a mail-only state, so this will work only if we encourage them to continue to produce data incorrectly, is something we'll want to stay aware of with any other state start conducting elections by mail. If this is a short-term fix, I think this is fine, but we'd need to update the hard-coding should any other states move to mail elections. 

As for the local election information, won't the full information still be visible below the pop-up? It's possible I'm misunderstanding the implementation here.  If you wanted to add additional fields to the pop-up, I'd probably use the "name" and "electionInfoUrl" from Elections Administration.

**Comment by MariaBianchi** [comment]
Good morning! 

It looks like the "mail-only" feature for the states where the entire election isn't run by mail was never updated with the changes Jared suggested back in August. 

The flags that pop-up in the two mail-only states, Oregon and Washington, which I believe are hard coded to trigger it, look great. These are the ones that offer the "Continue, Enter a Different Location, or Use Current Address" functionality.

For the other use case, where the message is triggered by the mail-only boolean in precinct from the API, the message should be a little different.

Currently, it looks like this. 
![screen shot 2016-06-06 at 8 45 11 am](https://cloud.githubusercontent.com/assets/7061871/15822621/d9d1b94a-2bc4-11e6-9525-050e62ebeaf9.png)

Ideally, the pop-up would be titled "Mail-in Voting Precinct" (In most cases where we're using the boolean, the entire state isn't using mail in voting. 

Like Jared said, ideally we'd want the "enter a different address" option removed as well as the "current location" feature"

If it's possible to use the text that Jen and Sean created, that would be helpful.

"Your upcoming election is mail-only. Please contact your local election official to learn more about how to receive and return your ballot:

[LEO INFORMATION. If none, State Election Administration Information]

This also means you may be able to return your ballot at multiple locations. Please hit continue to see your election information."

@acohen84 @rhoffmanpew

**Comment by acohen84** [comment]
I know that this means the translations won't match, but given the time, this change should be implemented.

**Comment by alexkonrad** [comment]
@MariaBianchi @acohen84 Ok, we will swap the copy and remove that different address button.

**Comment by alexkonrad** [comment]
@MariaBianchi @acohen84 do we have any California addresses currently triggering the `mailOnly` response that we can use for testing?

**Comment by alexkonrad** [comment]
Updated.
