### ISSUE TITLE
Adding closed primary functionality

### ISSUE THREAD

**Issue by jen-tolentino** [votinginfoproject/vip-embeddable-tool#157]
I just noticed that the functionality for closed primaries did not seem to get implemented last year.

Initial wire-frames:
![image](https://cloud.githubusercontent.com/assets/5825049/9450574/71709a30-4a77-11e5-96ec-43fd9abaf0bc.png)

If the election is a closed primary, this will come through the Civic API:
contests[].primaryParty	
(https://developers.google.com/civic-information/docs/v2/elections/voterInfoQuery)

You can view test data using this information:
EID: 4021
Test address: 1796 Egret St Sw, Shallotte, NC 28470

Also, rather than using the language included in the initial wireframes, we'd like it to be the following:

"Your upcoming election is partisan. Please select a party to view your ballot:"

You can also remove the text: "Only for registered [PARTY]"

Please let me know if you have any questions!

**Comment by alexkonrad** [comment]
We currently have the primary party information alongside the contest info in the ballot information tab, because the closed primaries aren't separate elections themselves but contests within an election. So if you input that address for the EID 4021, you'll see the primary party specified in the gray tabs on the right in the ballot information section. So the initial wireframes are incorrect regarding that. However, if this isn't the correct way to display it we can definitely change it to something else. Let me know!

**Comment by kthale** [comment]
@alexkonrad I tried the sample address and I'm seeing each party specified, but I'm seeing all parties for each contest, which I shouldn't for a closed primary--I should be able to select my party and only see the party candidate for that race. Does that make sense?

**Comment by yulheecho** [comment]
Hi @kthale ,

While we tried to accommodate everything in the wireframing phase, there were some edge cases that we needed to adjust in production as we received sample data that matched those edge cases.

In this case, the API returns closed primaries as a contest within an election, rather than an election of its own. The way that the wireframes display it is as if it is its own election (as we expected it to be returned by the API).

That being said, we should be able to make this adjustment before EOW with the following plan of action: check to see if any of the contests are closed primaries, then display the multiple election box saying “choose a party to view closed primaries" or "view all”.

Let us know if this works for you. Thanks!

**Comment by kthale** [comment]
Hi @yulheecho,

That sounds like a plan. Please let me know you if you run into any issues and we can troubleshoot together.

Thanks for addressing in a tight turnaround.

**Comment by yulheecho** [comment]
@kthale You got it, will do!

**Comment by yulheecho** [comment]
Hi @kthale - we're coming across a judgement call that we need to make in order to implement this functionality. Is there a time today or tomorrow you'd be available to jump on a call?

We're open at the times below:
Wed: 2-3:30PM EST, 4-5:30PM EST
Thu: 11AM-12PM EST

Let us know, thanks,

Yulhee

**Comment by kthale** [comment]
Hi @yulhee,

Of course--let's do Thursday at 11am EST. I'll send around an invite momentarily.

Thanks!

**Comment by yulheecho** [comment]
Perfect, thanks @kthale!

**Comment by alexkonrad** [comment]
@kthale This is implemented on [staging](https://s3.amazonaws.com/vip-voter-information-tool-staging/configurable.html). Please let us know any feedback. Thanks!

**Comment by kthale** [comment]
@alexkonrad sorry for the delay in responding. Looks good, but a few comments.

Can you change the buttons to a drop down menu option instead? In some states, like NY, there are quite a few parties, and creating buttons could be cumbersome. 

The buttons now don't read the full name of the party, which they should. Is this pulling from the feed directly? Can we fix this?

Also, we'd like to change the language to read: “This election is only open to registered members of the listed parties.  Please select your party to continue.” 

Thanks so much.

**Comment by alexkonrad** [comment]
@kthale FYI, the party name (e.g. "DEM", "REP") is just coming from returned data.

**Comment by kthale** [comment]
@alexkonrad that's what I thought--is there a work around to edit that?

**Comment by alexkonrad** [comment]
@kthale If you could provide us with some sort of mapping from terms like "DEM" or whatever could show up in the primaryParty field to other terms, then we can convert them when displaying the ballot information. This would be a good idea as long as the names in primaryParty field remained relatively consistent so we don't have to deal with a lot of edge cases.

And yes, we will change it to be a dropdown instead. Like you mentioned, that should be able to accommodate a large number of primary parties better than radio buttons.

**Comment by kthale** [comment]
@alexkonrad ok, after some research, I discovered it is highly likely that there will only be Democratic and Republican options for this, so I think keeping the buttons will be sufficient. Do you need mapping for these? Thanks for your patience.

**Comment by alexkonrad** [comment]
@kthale Ok, we can keep the buttons as is. You can send over the desired mapping when you're ready and we'll add that in. Thanks!

**Comment by alexkonrad** [comment]
Hi @kthale, I've added some basic mappings for the three parties (e.g., "DEM" to "Democratic Party") covered by the example which should be viewable on staging now.

**Comment by alexkonrad** [comment]
Hi @kthale, I pushed those changes live. I just added the text transformations for "LIB", "DEM", and "REP", so if you need more you can reopen this issue.
