### ISSUE TITLE
Addresses direct to polling location seemingly at random, ignoring closest polling location.

### ISSUE THREAD

**Issue by MariaBianchi** [votinginfoproject/vip-embeddable-tool#169]
Colorado says: "2557 S. Winona Ct., Denver, CO directed me to 200 W. 14th Ave. - Group residential facility Polling Location card information card appeared.  Should have directed me to 2120 S Tennyson as the closest polling place."

Interestingly, the Google VIT selects the Tennyson St polling location, making me think that this is coming through the API with proximity ordered.

Here’s the Google tool, in case that’s useful.

https://hidden.votinginfoproject.org/?election_id=4147&official_only=true&suppress_voter_id_rules=true

username: vipstaging
password: Vip Secret Staging Space

**Comment by MariaDemocracyWorks** [comment]
Other addresses demonstrating this behavior include 10728 Crystal Way, Conifer, CO and 100 Greenwood Blvd, Denver, CO. 

If you're able to fix the issue so that clicking the indicator in the key brings you to the nearest location of that type, that would go a long way towards fixing this problem.

**Comment by yulheecho** [comment]
Thanks @MariaDemocracyWorks We are looking into these issues in conjunction and will send an update as we find more information

**Comment by MariaDemocracyWorks** [comment]
Thank you for your help with this! Right now, this display issue is the thing keeping us from taking the CO data live, so I really appreciate being kept in the loop.

**Comment by kthale** [comment]
@yulheecho I am checking to see if there is any update here. Thanks so much!

**Comment by alexkonrad** [comment]
@MariaDemocracyWorks we're looking into a fix for this before tomorrow. If we can't find the appropriate fix before then I can temporarily disable this feature till we do so that you guys can get that data live.

**Comment by alexkonrad** [comment]
I updated the location legend to pan to the closest type of location. You should see this now reflected in the live tool

**Comment by MariaDemocracyWorks** [comment]
@alexkonrad Thank you, this helps!

**Comment by MariaDemocracyWorks** [comment]
@alexkonrad The legend now seems to be working properly, but the first address that loads seems to be randomized. What's causing that?

For 2557 S. Winona Ct., Denver CO, the first result loaded is the Group Residential Facility, which is a polling location around 8 miles away. There's another polling location only .8 miles away, which is what the tool should be directing too, even if it's going to display the closest polling location rather than the slightly closer drop box.

Based on how this address returns results in the old Google Tool (https://hidden.votinginfoproject.org/?election_id=4147&official_only=true&suppress_voter_id_rules=true), this doesn't appear to be an issue with the ordering coming from the API.  Is this something that can be fixed?

**Comment by alexkonrad** [comment]
The first result loaded by the tool is the first polling location in the returned list of polling locations. I couldn't use the Google Civic Info API explorer to take screenshots of this because it's staging data, so instead I just used my browser console. Here is what is being returned to me when I make an API call to that EID and address:
![image](https://cloud.githubusercontent.com/assets/4000470/10849581/cab5374a-7ef7-11e5-9d5c-c4b0baecf38f.png)
So if the Google tool is displaying the closest location correctly, it's either configured to get a differently ordered list of polling locations than I am, or it has some feature to order the locations itself. If it does, I'd be happy to take a look at the code and figure out how they're doing it so we can implement it.

**Comment by MariaDemocracyWorks** [comment]
@alexkonrad 
I checked into this, and you're right, this is an issue with what the Civic API returns. One last thing: Is it possible to fix the legend so the icons aren't stacking on top of eachother?

![screen shot 2015-10-30 at 3 31 03 pm](https://cloud.githubusercontent.com/assets/7061871/10856032/4f8b5c24-7f1b-11e5-869b-bdf972249a7b.png)

**Comment by MariaDemocracyWorks** [comment]
@alexkonrad URGENT: for some reason, if you give the tool time to load fully, the green flags indicating that a location is and Early Vote & Polling location site never appear.  Instead, the gray drop-off flags are covering all of the other markers, making it appear that Denver has no polling locations or early vote sites. 

![screen shot 2015-10-30 at 5 11 30 pm](https://cloud.githubusercontent.com/assets/7061871/10858245/e11f1636-7f29-11e5-976e-c23d7d88b486.png)

**Comment by alexkonrad** [comment]
@MariaDemocracyWorks I'm looking into this now.

Something I can say so far is that the tool merges different types of locations by comparing their address lines. I've already added logic to replace periods, ignore casing, and things like that, but some of these locations which are the same have different address lines. For example, the polling location listed here as an address "200 W 14th AVE SUITE 100", but then the drop-off location has an address "200 W 14th Ave Ste 100." Unless we add more rules for comparing addresses the tool won't know that these are the same location, so it will place the drop-off pin on top of the other pins (as you're seeing here).

For another example, one has "MULTIPURPOSE ROOM 2880 OSCEOLA ST" and another has "2880 N Osceola St" as their address lines. It would be difficult for me to add all the possible rules with which we could merge these locations into one.

**Comment by MariaDemocracyWorks** [comment]
I completely understand why that is hard. Is that what's happening in every case? Even if we can't solve this completely, improving it a little would help, so that you could tell there were more than just drop boxes.

I'll work on manually cleaning the data as well.

**Comment by alexkonrad** [comment]
I'll try to look at every location for that address to see if there's a bug in there which is causing that to happen for all locations. I can also add additional matching rules, or even something like testing containment (like seeing if "2880 OSCEOLA" is contained in "MULTIPURPOSE ROOM 2880 OSCEOLA ST") to match more locations, but then there's the caveat that this might also make different locations appear to be identical (I'm not sure how likely this is, but it's a possibility as long as we're not testing strict equality anymore).

**Comment by MariaDemocracyWorks** [comment]
Thank you, Alex! Adding a containment rule sounds like it could help.

**Comment by MariaDemocracyWorks** [comment]
One more question: Do the Location names need to match, or only the addresses?

**Comment by alexkonrad** [comment]
@MariaDemocracyWorks only addresses

**Comment by MariaDemocracyWorks** [comment]
Thank god. That makes this so much easier.
