### ISSUE TITLE
Show home drop pin and more than one drop pin in the default view

### ISSUE THREAD

**Issue by lbirdpew** [votinginfoproject/vip-embeddable-tool#208]
When a good address is returned, we would like to show the drop pin for the searched address and up to the nearest 5 drop pins around that address to include polling places, early vote sites, and drop boxes.

Let me know if this needs greater clarification.

**Comment by afsmythe** [comment]
Hello. We have been notified by some states of an issue which should be solved by @lbirdpew request here. For a drop box state such as Oregon drop boxes for a good address are loaded, however some drop boxes which are close to the voter address are loaded after drop boxes which are further away. As a test please use "1320 East Edgewood Drive Newberg OR 97132". 

We would expect the "Newberg Public Safety" drop box (id 9362) to load immediately, however it is not loading until after ~20 other drop boxes load. The tool is zoomed out considerably from the voter address in this test. 

Any ideas what might be causing this delay?

**Comment by alexkonrad** [comment]
Initial map load for "1320 East Edgewood Drive Newberg OR 97132" should now look like this: 
![image](https://cloud.githubusercontent.com/assets/4000470/19499466/765aa002-954b-11e6-8319-d38abb6f4693.png)

- The tool now extends the map bounds to the five nearest locations of any type. This may not be exact because we do not have geolocation data for all locations on initial map load.

- @afsmythe In this instance the tool was confusing 5-digit zipcodes with 9-digit zipcodes and not pre-sorting them correctly. The tool groups the locations by zipcode to try to determine the closest location of _any_ type before we receive time-delayed geolocation data (the Civic Information API returns locations sorted by distance but grouped according to a location's respective type). This should fix it for this address but if there are other instances of this behavior that this patch does not fix please let us know.
