### ISSUE TITLE
Support Request

### ISSUE THREAD

**Issue by lbirdpew** [votinginfoproject/vip-embeddable-tool#212]
**Below is a support request we received via email this morning.  Any idea what they're doing wrong?**

Hello - Thanks so much for your tool to help voters find their polling place.  I'm having trouble installing it on a Wordpress site.   I just paste the embed code into a post or page, right?
I'm getting this:
https://toppac.org/173-2/
After pasting in this:
```
<script type="text/javascript" src="https://tool.votinginfoproject.org/app.js"></script>
<div id="_vit"></div>
<script type="text/javascript">vit.load({
    modal: true,
    theme: 'https://tool.votinginfoproject.org/images/theme3.png',
    title: 'Find Your Polling Place',
    subtitle: 'Be Prepared to Vote',
    width: '640px',
    height: '480px',
    logo: '//upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Seal_of_Texas.svg/170px-Seal_of_Texas.svg.png',
    colors: {
      'header': '#229acd',
      'landscapeBackgroundHeader': '#228a9d'
    },
    language: 'en',
});</script>
```

Would really appreciate any help.   Thank you!

**Comment by alexkonrad** [comment]
It looks like WordPress is filtering the Javascript tags out. As a preliminary step, have you tried selecting the "Text" tab (instead of "Visual") when pasting in the code in the WordPress content authoring panel?

If that doesn't work, for additional troubleshooting: can you say whether the WordPress user you're using is an admin, author, or some other role? What version of WordPress are you using.

**Comment by lbirdpew** [comment]
Dude never replied.  Closing.
