### ISSUE TITLE
Polling Place Zoomed Out on Staging

### ISSUE THREAD

**Issue by lbirdpew** [votinginfoproject/vip-embeddable-tool#229]
Hey team,

On the staging server, when testing 34365 Mud Springs Road, Black Canyon City, AZ, 85324, the map is appearing at an extremely wide zoom.  

I'm not seeing it in other states.

**Comment by alexkonrad** [comment]
@lbirdpew by staging server do you mean setting the parameter `productionDataOnly` to false? I'm trying to reproduce this.

**Comment by alexkonrad** [comment]
Updated. The map bounds were extended to be arbitrarily large because the tool uses zip codes to calculate bounds and some of the first five locations don't have zip codes (we cannot use lat/lng data because we need to wait for the API response for that information).

![image](https://cloud.githubusercontent.com/assets/4000470/19954542/3371ea9c-a136-11e6-84e3-10504b2f2524.png)

**Comment by lbirdpew** [comment]
Perfect.  Thanks.  sorry for the slow response, my github emails were being strange for the past day.  resolved now.
